"use client";

import React, { useState } from "react";
import { InvestigationResponse, InvestigationEvidenceTrace } from "@/types/investigation";
import { getStatusLabel, getValidationStatusLabel, formatCheckName, formatAmount } from "@/lib/formatters";

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  investigation: InvestigationResponse;
  trace?: InvestigationEvidenceTrace | null;
}

export function ExportReportModal({
  isOpen,
  onClose,
  investigation,
  trace,
}: ExportReportModalProps) {
  const [copied, setCopied] = useState(false);
  const [format, setFormat] = useState<"markdown" | "json">("markdown");

  if (!isOpen) return null;

  const markdownReport = `# ExceptionLineage Invoice Investigation Report

- **Invoice**: ${investigation.invoice_id}
- **Customer**: ${investigation.customer_name || investigation.customer_id || "Unavailable"}
- **Amount**: ${formatAmount(investigation.amount, investigation.currency || "USD")}
- **Finding**: ${getStatusLabel(investigation.status)}
- **Date**: ${investigation.created_at}
- **Investigation Ref**: ${investigation.investigation_id}
- **Supporting Records Cited**: ${investigation.cited_evidence_ids?.join(", ") || "None"}

---

## Finding & Summary
${investigation.summary || "No summary recorded."}
${investigation.failure_reason ? `\n**Context / Notes**:\n${investigation.failure_reason}` : ""}

---

## Verification Checks
${
  investigation.validation_results && investigation.validation_results.length > 0
    ? investigation.validation_results
        .map(
          (r) =>
            `- [${getValidationStatusLabel(r.status)}] **${formatCheckName(r.check_name)}**: ${r.message || "Evaluated"} ${
              r.evidence_ids && r.evidence_ids.length > 0
                ? `(Citations: ${r.evidence_ids.join(", ")})`
                : ""
            }`
        )
        .join("\n")
    : "No verification checks recorded."
}

---

## Contract History
- **Governing Contract**: ${investigation.lineage?.contract?.title || investigation.lineage?.contract?.id || "None"}
- **Amendments**: ${investigation.lineage?.amendments?.map((a) => a.id).join(", ") || "None"}
- **SOWs**: ${investigation.lineage?.sows?.map((s) => s.id).join(", ") || "None"}
- **Operational Approval**: ${investigation.lineage?.approval?.status || "None"} (${investigation.lineage?.approval?.approver || "—"})

---

## Supporting Records
${
  investigation.lineage?.evidence && investigation.lineage.evidence.length > 0
    ? investigation.lineage.evidence
        .map(
          (ev) =>
            `### Record ${ev.id}: ${ev.title || ev.evidence_type}
- **Type**: ${ev.evidence_type}
- **Source**: ${ev.source} (ID: ${ev.source_id})
- **Locator / Section**: ${ev.locator || "—"}
- **Excerpt**: "${ev.excerpt || "—"}"`
        )
        .join("\n\n")
    : "No supporting records returned in lineage."
}

---
*Report generated by ExceptionLineage — Invoice Investigation.*
`;

  const jsonReport = JSON.stringify(
    {
      investigation,
      trace,
      exported_at: new Date().toISOString(),
    },
    null,
    2
  );

  const activeContent = format === "markdown" ? markdownReport : jsonReport;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = `invoice-review-${investigation.invoice_id}.${
      format === "markdown" ? "md" : "json"
    }`;
    const blob = new Blob([activeContent], {
      type: format === "markdown" ? "text/markdown" : "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-xs p-4 overflow-y-auto"
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl rounded-xl border border-slate-200 bg-white p-6 shadow-2xl space-y-4"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between pb-3 border-b border-slate-100">
          <div>
            <h2 className="text-base font-bold text-slate-900 tracking-tight">
              Export Investigation Report
            </h2>
            <p className="text-xs text-slate-500">
              Invoice {investigation.invoice_id}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 p-1"
          >
            ✕
          </button>
        </div>

        {/* Format Selector */}
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setFormat("markdown")}
            className={`px-3 py-1.5 rounded-md text-xs font-semibold transition ${
              format === "markdown"
                ? "bg-slate-900 text-white shadow-2xs"
                : "bg-slate-100 text-slate-600 hover:bg-slate-200"
            }`}
          >
            Markdown (.md)
          </button>
          <button
            type="button"
            onClick={() => setFormat("json")}
            className={`px-3 py-1.5 rounded-md text-xs font-semibold transition ${
              format === "json"
                ? "bg-slate-900 text-white shadow-2xs"
                : "bg-slate-100 text-slate-600 hover:bg-slate-200"
            }`}
          >
            JSON Raw Payload (.json)
          </button>
        </div>

        {/* Content Preview */}
        <div className="rounded-lg border border-slate-200 bg-slate-50 p-3 max-h-80 overflow-y-auto font-mono text-[11px] text-slate-800 whitespace-pre-wrap leading-relaxed">
          {activeContent}
        </div>

        {/* Actions */}
        <div className="flex items-center justify-between pt-3 border-t border-slate-100 text-xs">
          <span className="text-slate-500 font-mono text-[11px]">
            {activeContent.length.toLocaleString()} characters
          </span>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={handleCopy}
              className="px-3.5 py-2 rounded-md border border-slate-200 text-slate-700 hover:bg-slate-50 font-semibold transition"
            >
              {copied ? "✓ Copied to Clipboard" : "Copy to Clipboard"}
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="px-4 py-2 rounded-md bg-slate-900 text-white font-semibold hover:bg-slate-800 transition"
            >
              Download Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
